import type { Crew, Lead, Service } from "./types";

export const AREAS_SC = [
  "Shandon",
  "Forest Acres",
  "Earlewood",
  "Rosewood",
  "St. Andrews",
  "Irmo",
  "Lexington",
  "West Columbia",
  "Cayce",
  "Northeast",
  "Dentsville",
  "Blythewood",
  "Chapin",
  "Ballentine",
  "Elgin",
  "Lugoff",
  "Seven Oaks",
];

export const AREAS_PR = [
  "San Juan",
  "Bayamón",
  "Carolina",
  "Guaynabo",
  "Caguas",
  "Trujillo Alto",
  "Toa Baja",
  "Dorado",
  "Ponce",
  "Río Piedras",
];

export const COLUMBIA_ZIPS = new Set([
  "29201", "29203", "29204", "29205", "29206", "29209", "29210", "29212",
  "29223", "29229", "29072", "29073", "29063", "29033", "29036", "29169",
  "29170", "29172", "29016", "29078", "29044", "29053", "29054", "29203",
]);

export const SERVICES: Service[] = [
  {
    id: "lawn",
    minutes: 75,
    photo: "/photos/lawn.jpg",
    prices: { small: 49, medium: 69, large: 89 },
  },
  {
    id: "driveway",
    minutes: 60,
    photo: "/photos/split.jpg",
    prices: { small: 119, medium: 149, large: 189 },
  },
  {
    id: "housewash",
    minutes: 150,
    photo: "/photos/hero.jpg",
    prices: { small: 229, medium: 299, large: 389 },
  },
  {
    id: "gutters",
    minutes: 90,
    photo: "/photos/gutters.jpg",
    prices: { small: 129, medium: 169, large: 219 },
  },
  {
    id: "mulch",
    minutes: 120,
    photo: "/photos/pr.jpg",
    prices: { small: 159, medium: 219, large: 299 },
  },
  {
    id: "paint",
    minutes: 0,
    photo: "/photos/arrive.jpg",
    prices: { small: 0, medium: 0, large: 0 },
  },
  {
    id: "handyman",
    minutes: 90,
    photo: "/photos/gutters.jpg",
    prices: { small: 89, medium: 149, large: 229 },
  },
];

export const CREWS: Crew[] = [
  {
    id: "luis",
    name: "Luis Rivera",
    slug: "rivera-wash",
    trade: "Pressure + gutters",
    trades: ["driveway", "housewash", "gutters"],
    market: "columbia",
    areas: ["Forest Acres", "Shandon", "Northeast", "Dentsville"],
    rating: 4.9,
    jobs: 214,
    etaMin: 18,
    photo: "/photos/arrive.jpg",
    bio: "Shows up in a marked truck. Sends before/after photos before he leaves the driveway.",
    bioEs: "Llega en camión marcado. Manda fotos del antes y después antes de irse.",
    bilingual: true,
  },
  {
    id: "keisha",
    name: "Keisha Boone",
    slug: "boone-lawn",
    trade: "Lawn + beds",
    trades: ["lawn", "mulch"],
    market: "columbia",
    areas: ["Irmo", "Chapin", "Ballentine", "Lexington"],
    rating: 4.8,
    jobs: 341,
    etaMin: 22,
    photo: "/photos/lawn.jpg",
    bio: "Weekly and one-off cuts. Edges the sidewalk. Does not ghost on rainy Mondays.",
    bioEs: "Cortes semanales y sueltos. Orilla la acera. No desaparece los lunes de lluvia.",
    bilingual: false,
  },
  {
    id: "marcus",
    name: "Marcus Hill",
    slug: "hill-crew",
    trade: "Wash + lawn",
    trades: ["lawn", "driveway", "housewash"],
    market: "columbia",
    areas: ["West Columbia", "Cayce", "Lexington", "Rosewood"],
    rating: 4.7,
    jobs: 168,
    etaMin: 14,
    photo: "/photos/hero.jpg",
    bio: "Same-day driveway washes when the board is open. Price on the app is the price on the invoice.",
    bioEs: "Lavado de entrada el mismo día si hay cupo. El precio de la app es el de la factura.",
    bilingual: false,
  },
  {
    id: "ana",
    name: "Ana Cruz",
    slug: "cruz-yard",
    trade: "Lawn · bilingual",
    trades: ["lawn", "mulch", "gutters"],
    market: "columbia",
    areas: ["St. Andrews", "Irmo", "West Columbia"],
    rating: 5.0,
    jobs: 96,
    etaMin: 27,
    photo: "/photos/pr.jpg",
    bio: "English or Spanish on the job. Building the San Juan roster next.",
    bioEs: "Inglés o español en el trabajo. Armando el equipo de San Juan después.",
    bilingual: true,
  },
  {
    id: "jamal",
    name: "Jamal Wright",
    slug: "wright-atlanta",
    trade: "Lawn · Atlanta",
    trades: ["lawn", "mulch"],
    market: "atlanta",
    areas: ["East Point", "Decatur", "Buckhead"],
    rating: 4.9,
    jobs: 502,
    etaMin: 16,
    photo: "/photos/lawn.jpg",
    bio: "Platinum crew. Edges, bags, texts when he turns onto your street.",
    bioEs: "Equipo Platinum. Orilla, embolsa, avisa al doblar a tu calle.",
    bilingual: false,
    tier: "platinum",
  },
  {
    id: "sofia",
    name: "Sofía Méndez",
    slug: "mendez-miami",
    trade: "Wash · Miami",
    trades: ["driveway", "housewash", "gutters"],
    market: "miami",
    areas: ["Little Havana", "Coral Gables", "Doral"],
    rating: 4.8,
    jobs: 276,
    etaMin: 15,
    photo: "/photos/hero.jpg",
    bio: "Soft wash that does not strip paint. Spanish or English.",
    bioEs: "Lavado suave que no quita pintura. Español o inglés.",
    bilingual: true,
    tier: "gold",
  },
  {
    id: "derek",
    name: "Derek Cole",
    slug: "cole-dallas",
    trade: "Full yard · Dallas",
    trades: ["lawn", "driveway", "gutters", "handyman"],
    market: "dallas",
    areas: ["Oak Cliff", "Plano", "Uptown"],
    rating: 4.7,
    jobs: 188,
    etaMin: 19,
    photo: "/photos/street.jpg",
    bio: "Same-day driveway and lawn when the board is red.",
    bioEs: "Entrada y césped el mismo día cuando la pizarra está roja.",
    bilingual: false,
    tier: "gold",
  },
  {
    id: "nori",
    name: "Nori Park",
    slug: "park-la",
    trade: "House wash · LA",
    trades: ["housewash", "driveway", "gutters"],
    market: "los-angeles",
    areas: ["Koreatown", "Pasadena", "Long Beach"],
    rating: 5.0,
    jobs: 144,
    etaMin: 21,
    photo: "/photos/split.jpg",
    bio: "Before/after on every elevation. No surprise add-ons.",
    bioEs: "Antes y después en cada fachada. Sin extras sorpresa.",
    bilingual: true,
    tier: "platinum",
  },
  {
    id: "edgardo",
    name: "Edgardo Vázquez",
    slug: "vazquez-sj",
    trade: "Grama + lavado · San Juan",
    trades: ["lawn", "driveway", "housewash"],
    market: "san-juan",
    areas: ["Santurce", "Condado", "Río Piedras", "Guaynabo"],
    rating: 4.9,
    jobs: 131,
    etaMin: 18,
    photo: "/photos/pr.jpg",
    bio: "WhatsApp updates. ATH Móvil when we flip that switch. Corte de grama, not a mainland script.",
    bioEs: "Updates por WhatsApp. ATH Móvil cuando se active. Corte de grama de verdad.",
    bilingual: true,
    tier: "platinum",
  },
];

export const SEED_LEADS: Lead[] = [
  {
    id: "L-001",
    createdAt: Date.now() - 86400000 * 3,
    name: "Turtle Shell Pressure Washing",
    trade: "Pressure washing",
    city: "Columbia, SC 29209",
    market: "columbia",
    phone: "(803) 413-9930",
    website: "",
    source: "Yelp / Google public listing",
    notes: "Public directory. Weak/no own site. Verify before calling. Do not auto-text.",
    status: "new",
    script: "",
    demoSlug: "",
  },
  {
    id: "L-002",
    createdAt: Date.now() - 86400000 * 2,
    name: "Jackson’s Pressure Washing, LLC",
    trade: "Pressure washing",
    city: "Columbia, SC",
    market: "columbia",
    phone: "(803) 618-9943",
    website: "https://jacksonspressurewashingllc.com/",
    source: "Public site (GoDaddy builder)",
    notes: "Has a thin site. Pitch booking + locked price, not “you have no website.”",
    status: "new",
    script: "",
    demoSlug: "",
  },
  {
    id: "L-003",
    createdAt: Date.now() - 86400000,
    name: "Lawn Pros of the Midlands",
    trade: "Lawn",
    city: "Columbia, SC",
    market: "columbia",
    phone: "(803) 661-0312",
    website: "https://www.lawnprosofthemidlands.com/",
    source: "Public Wix site",
    notes: "Wix + Instagram. Good candidate for live tracking + deposit.",
    status: "new",
    script: "",
    demoSlug: "",
  },
  {
    id: "L-004",
    createdAt: Date.now() - 3600000 * 20,
    name: "Midlands Extreme Lawn Care",
    trade: "Lawn",
    city: "Columbia, SC",
    market: "columbia",
    phone: "(803) 748-6821",
    website: "",
    source: "Yelp public listing",
    notes: "Facebook-heavy / thin web. Confirm which phone is current.",
    status: "new",
    script: "",
    demoSlug: "",
  },
  {
    id: "L-005",
    createdAt: Date.now() - 3600000 * 18,
    name: "Old South Landscaping LLC",
    trade: "Lawn + landscaping",
    city: "Lexington, SC 29073",
    market: "columbia",
    phone: "(803) 513-3360",
    website: "",
    source: "Houzz public listing",
    notes: "Directory presence, no strong own site confirmed.",
    status: "new",
    script: "",
    demoSlug: "",
  },
  {
    id: "L-006",
    createdAt: Date.now() - 3600000 * 12,
    name: "Cut M Up Lawn and Tree Service",
    trade: "Lawn + tree",
    city: "Columbia, SC 29223",
    market: "columbia",
    phone: "(803) 865-9833",
    website: "",
    source: "BBB public listing",
    notes: "Northeast Columbia. Verify before calling.",
    status: "new",
    script: "",
    demoSlug: "",
  },
  {
    id: "L-007",
    createdAt: Date.now() - 3600000 * 8,
    name: "Island Pro Pressure Washing",
    trade: "Pressure washing",
    city: "Puerto Rico (island-wide)",
    market: "puerto-rico",
    phone: "787-223-9664",
    website: "https://islandpropr.com/",
    source: "Public site · WhatsApp CTA",
    notes: "PR waitlist only until Columbia has ~20 jobs. They already live on WhatsApp — match that.",
    status: "new",
    script: "",
    demoSlug: "",
  },
  {
    id: "L-008",
    createdAt: Date.now() - 3600000 * 6,
    name: "JBP Pressure Washing",
    trade: "Pressure washing",
    city: "Bayamón, PR",
    market: "puerto-rico",
    phone: "939-231-9633",
    website: "",
    source: "InfoPaginas directory",
    notes: "No site found. PR later. WhatsApp + ATH Móvil, not Stripe-only.",
    status: "new",
    script: "",
    demoSlug: "",
  },
];

export function serviceById(id: string) {
  return SERVICES.find((s) => s.id === id);
}

export function crewById(id: string) {
  return CREWS.find((c) => c.id === id);
}

export function pickCrew(service: string, zip: string) {
  const match = CREWS.filter((c) =>
    c.trades.includes(service as Crew["trades"][number]),
  );
  const pool = match.length ? match : CREWS;
  const n = zip.split("").reduce((a, ch) => a + ch.charCodeAt(0), 0);
  return pool[n % pool.length];
}
